# Generated by Django 5.0.4 on 2025-06-20 01:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraper',
            name='last_scraped',
        ),
        migrations.RemoveField(
            model_name='scraper',
            name='name',
        ),
        migrations.AddField(
            model_name='scraper',
            name='keyword',
            field=models.CharField(default='default_keyword', max_length=100),
        ),
        migrations.AddField(
            model_name='scraper',
            name='price',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='scraper',
            name='product_name',
            field=models.CharField(default='default_product_name', max_length=255),
        ),
        migrations.AddField(
            model_name='scraper',
            name='scraped_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
