# Generated by Django 5.0.4 on 2025-06-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_remove_scraper_last_scraped_remove_scraper_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='site',
            field=models.CharField(default='default_site', max_length=100),
        ),
    ]
