# Generated by Django 5.0.4 on 2025-06-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_scraper_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='img',
            field=models.URLField(default='https://example.com/default_image.jpg'),
        ),
    ]
